spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/jwttest?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '!Cdh04860'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080

cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: "??? ? ??"
      secret-key: "??? ? ??"
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error"

aws:
  s3:
    bucket: "Bucket ?? ??"
